[parity]
base_path = "/opt/apollo"
mode = "active"
chain = "/opt/apollo/chain.json"
# chain = "chain.json"

[footprint]
cache_size_db = 100
pruning = "fast"

[network]
warp = false
nat = "extip:10.0.0.15"
# reserved_peers = "/opt/apollo/reserved.txt"

[rpc]
apis = ["web3", "eth", "net", "parity", "traces"]
interface = "all"
cors = ["*"]

[websockets]
apis = ["web3", "eth", "pubsub", "net"]
interface = "all"
origins = ["all"]

[ipc]
disable = true

[account]
password = ["/opt/apollo/password"]
# password = ["password"]

[mining]
engine_signer = "0x1665a5a9671f046a73cdb66c0799f5eb407d866c"
reseal_on_txs = "none"
force_sealing = true
extra_data = "Apollo v3.3.3-amb1.0.1"
